---
title: FIMS Team
toc: true
toc-location: left
toc-depth: 2
---

FIMS is a collaborative effort that would not be possible without the generous support of NOAA Fisheries and its employees as well as members of the FIMS Council.

## Core Developers

* Kelli F. Johnson (OST)
* Jon K. T. Brodziak (PIFSC)
* Kathryn L. Doering (OST)
* Andrea M. Havron (OST)
* Alexander J. Jensen (SWFSC)
* Ronald Klasky (T and T Consulting Services, Inc.)
* Peter T. Kuriyama (SWFSC)
* Christopher M. Legault (NEFSC)
* Bai Li (OST)
* Timothy J. Miller (NEFSC)
* Cole C. Monnahan (AFSC)
* Megumi C. Oshima (PIFSC)
* Kyle W. Shertzer (SEFSC)
* Jane Y. Sullivan (AFSC)
* Matthew Supernaw (OST)
* Ian G. Taylor (NWFSC)
* Eric J. Ward (NWFSC)
* Nathan R. Vaughan (Vaughan Analytics)

## Subject-Matter Experts

* Howard Townsend (OST)
* James N. Ianelli (AFSC)
* Lisa Pfeiffer (NWFSC)
* Patrick D. Lynch (OST)
* Richard D. Methot (NWFSC)

## Contributors

* Jennifer S. Bigman (University of Delaware)
* Kristan Blackhart (NEFSC)
* Edward J. Dick (SWFSC)
* Alan C. Haynie (ICES)
* Hui-hua Lee (SWFSC)
* Christine C. Stawitz (University of Birmingham)

## FIMS Council

* Anders Nielsen (DTU-Aqua)
* André E. Punt (Chair, SAFS UW)
* Anne M. Cooper (ICES)
* Bjarki Þ. Elvarsson (MFRI, Gadget)
* Curry J. Cunningham (NPFMC)
* Éva E. Plagányi (CSIRO)
* Geneviève M. Nesslage (Mid-Atlantic)
* Henning Winker (JRC, Jabba)
* Jim N. Sanchirico (UC Davis)
* Jon R. Weidenmann (Rutgers)
* Mark N. Maunder (IATTC)
* Z. Teresa A'mar (Dragonfly Data Science)

## Roles

### Project Lead

The Project Lead is responsible for driving decisions based on the vision and objectives of FIMS as directed in the [Terms of Reference](FIMS_TOR_08.26.2021.pdf) and discussions with the Implementation Team. The Project Lead ensures the FIMS product satisfies user and business requirements, incorporates feedback, and iterates on the design and development as needed. The Project Lead will triage issues and pull requests and ensure development and code review occur in a timely manner and according to project guidelines, priorities, and standards. The Project Lead is also responsible for communicating project status via maintenance of the [Github Projects](https://github.com/orgs/NOAA-FIMS/projects) and [GitHub Milestones](https://github.com/NOAA-FIMS/FIMS/milestones).

### Lead Software Architect

The Lead Software Architect is responsible for advising the architecture of FIMS to maximize portability and extensibility; manage technical risks and opportunities; advise the Project Lead on software design, refactor, and implementation decisions; and guarantee quality of deliveries via code review. The Lead Software Architect also educates the team on technical best practices.

### Lead Test Engineer

The Lead Test Engineer is responsible for designing and driving test objectives, test strategies, and test plans of the FIMS product at subsequent milestones. The Lead Test Engineer will identify the tools for test reporting, management and automation, guide and monitor the design, implementation, and execution of test cases and test procedures. The Lead Test Engineer will train and mentor implementation team members on how to effectively write and debug tests.

### Lead Statistical Computing Engineer

The Lead Statistical Computing Engineer is responsible for designing the FIMS statistical architecture that maximizes statistical accuracy and ensures the implementation of statistical good practices. The Lead Statistical Computing Engineer will advise the Project Lead on design and implementation decisions and will work closely with the Lead Software Architect to ensure a balance between computation and statistical efficiency and with the Lead Test Engineer to develop tests that check the statistical accuracy of model design. 

### Outreach and Transition Coordinator

The Outreach and Transition Coordinator communicates with policy-makers, NOAA leadership, and regional offices on transition plans from existing assessment models and processes to FIMS. This coordinator works with academic partners to develop and coordinate training on using FIMS.

### Lead of Workflows, Accessibility, and Integration

The Lead of Workflows, Accessibility, and Integration is responsible for designing and driving workflows and automation to support the reliability and robustness of the FIMS. The Lead of Workflows, Accessibility, and Integration ensures FIMS aligns with expected standards for accessibility and quality control in accordance with guidelines set by the Fisheries Integrated Toolbox. This lead coordinates with the Lead Test Engineer to ensure test cases are automated and successfully run by GitHub Actions and coordinates with the Lead Statistical Computing Engineer to identify opportunities to expand FIMS across related disciplines. 

### Regional Representatives

Regional Representatives are expected to assist in FIMS implementation through design, development, and testing of FIMS. They also communicate FIMS progress and design to their respective regions and teammates. Representatives serve as power users who provide basic training and outreach within their centers on transitioning to FIMS. These representatives are also responsible for relaying feedback, questions, and training requests that they cannot complete back to the Project Lead. Regional representatives are expected to introduce their partner fishery management organizations to FIMS to assist transition of FIMS from research to operations.

## Authorship

Current developers of FIMS are listed above and in the relevant DESCRIPTION files within repositories that store R packages, e.g., [FIMS DESCRIPTION](https://github.com/NOAA-FIMS/FIMS/blob/main/DESCRIPTION). When publications or presentations are developed using FIMS, the authors should feel free to list only those who contributed to that publication or presentation in whatever order they collectively see fit.
