---
title: FIMS Team
---

FIMS is a collaborative effort that would not be possible without the generous support of NOAA Fisheries and its employees as well as members of the FIMS Council.

## Core Developers

* Kelli F. Johnson (OST)
* Jon K. T. Brodziak (PIFSC)
* Kathryn L. Doering (OST)
* Andrea M. Havron (OST)
* Alexander J. Jensen (SWFSC)
* Ronald Klasky (T and T Consulting Services, Inc.)
* Peter T. Kuriyama (SWFSC)
* Christopher M. Legault (NEFSC)
* Bai Li (OST)
* Timothy J. Miller (NEFSC)
* Cole C. Monnahan (AFSC)
* Megumi C. Oshima (PIFSC)
* Kyle W. Shertzer (SEFSC)
* Jane Y. Sullivan (AFSC)
* Matthew Supernaw (OST)
* Ian G. Taylor (NWFSC)
* Eric J. Ward (NWFSC)
* Nathan R. Vaughan (Vaughan Analytics)

## Subject-Matter Experts

* Howard Townsend (OST)
* James N. Ianelli (AFSC)
* Lisa Pfeiffer (NWFSC)
* Patrick D. Lynch (OST)
* Richard D. Methot (NWFSC)

## Contributors

* Jennifer S. Bigman (University of Delaware)
* Kristan Blackhart (NEFSC)
* Edward J. Dick (SWFSC)
* Alan C. Haynie (ICES)
* Hui-hua Lee (SWFSC)
* Christine C. Stawitz (University of Birmingham)

## FIMS Council

* Anders Nielsen (DTU-Aqua)
* André E. Punt (Chair, SAFS UW)
* Anne M. Cooper (ICES)
* Bjarki Þ. Elvarsson (MFRI, Gadget)
* Curry J. Cunningham (NPFMC)
* Éva E. Plagányi (CSIRO)
* Geneviève M. Nesslage (Mid-Atlantic)
* Henning Winker (JRC, Jabba)
* Jim N. Sanchirico (UC Davis)
* Jon R. Weidenmann (Rutgers)
* Mark N. Maunder (IATTC)
* Z. Teresa A'mar (Dragonfly Data Science)
