---
title: "Implementing New Features in FIMS: A Case Study in Selectivity"
subtitle: "How to add new features in FIMS using existing code, GitHub, GitHub issues, and FIMS Implementation Team resources"
author: "Alexander Jensen and Emily Liljestrand"
date: "June 10, 2026"
categories:
   - learn
   - R
   - open-science
   - testing
editor: 
  markdown: 
    wrap: 72
format:
  html:
    echo: true
    code-fold: true
from: markdown+emoji
---

## Contributing to FIMS

The advantage of having a modular modeling system like FIMS is that the
development can also be broken down and tackled in component parts. By
utilizing github's collaborative tools, while one developer can focus on
improving recruitment estimates in FIMS, others can tackle, for example,
age composition likelihoods or diagnostic tools.

In this way, researchers at different centers can focus on adding those
features that are critically necessary to make the assessments in their
regions compatible with the FIMS platform. Our small team chipped off a
little piece of age-based stock assessment models that was important for
our two regions despite being on complete opposite sides of the country,
at the Southwest Fisheries Science Center and the Northeast Fisheries
Science Center.

The default selectivity option in FIMS is logistic or double logistic,
but the double normal or age-specific selectivity are used in stock
synthesis (SS) and the Woods Hole Assessment Model (WHAM) respectively.
We set out to add these options and remove one more barrier to
replicating regional assessments in FIMS.

## Our step-by-step contribution process

### Starting out

Though daunting at first, we realized we could add these selectivity
options by using existing scaffolding from previous selectivity options
or even recruitment or abundance options. Implementing new cpp
architecture was the most tricky, since neither of us had a strong
background in it.

inst/include/interface/rcpp/rcpp_objects/rcpp_selectivity.hpp. This code
is an RCPP interface to declare different types of selectivity. There
was already code for LogisticSelectivityInterface and
DoubleLogisticSelectivityInterface so it was trivial to copy this
architecture wholesale for "AgeSpecificSelectivityInterface"

LogisticSelectivityInterface:

``` cpp
#| echo: true
#| eval: false
#| code-fold: true
#| code-summary: "Show the code"

class LogisticSelectivityInterface : public SelectivityInterfaceBase {
 public:
  /**
   * @brief The index value at which the response reaches 0.5.
   */
  ParameterVector inflection_point;
  /**
   * @brief The width of the curve at the inflection point.
   */
  ParameterVector slope;

  /**
   * @brief The constructor.
   */
  LogisticSelectivityInterface() : SelectivityInterfaceBase() {
    SelectivityInterfaceBase::live_objects[this->id] =
        std::make_shared<LogisticSelectivityInterface>(*this);
    FIMSRcppInterfaceBase::fims_interface_objects.push_back(
        SelectivityInterfaceBase::live_objects[this->id]);
  }

  /**
   * @brief Construct a new Logistic Selectivity Interface object
   *
   * @param other
   */
  LogisticSelectivityInterface(const LogisticSelectivityInterface &other)
      : SelectivityInterfaceBase(other),
        inflection_point(other.inflection_point),
        slope(other.slope) {}

  /**
   * @brief The destructor.
   */
  virtual ~LogisticSelectivityInterface() {}

  /**
   * @brief Gets the ID of the interface base object.
   * @return The ID.
   */
  virtual uint32_t get_id() { return this->id; }

  /**
   * @brief Evaluate selectivity using the logistic function.
   * @param x The independent variable in the logistic function (e.g., age or
   * size in selectivity).
   */
  virtual double evaluate(double x) {
    fims_popdy::LogisticSelectivity<double> LogisticSel;
    LogisticSel.inflection_point.resize(1);
    LogisticSel.inflection_point[0] = this->inflection_point[0].initial_value_m;
    LogisticSel.slope.resize(1);
    LogisticSel.slope[0] = this->slope[0].initial_value_m;
    return LogisticSel.evaluate(x);
  }

  /**
   * @brief Extracts derived quantities back to the Rcpp interface object from
   * the Information object.
   */
  virtual void finalize() {
    if (this->finalized) {
      // log warning that finalize has been called more than once.
      FIMS_WARNING_LOG("Logistic Selectivity  " + fims::to_string(this->id) +
                       " has been finalized already.");
    }

    this->finalized = true;  // indicate this has been called already

    std::shared_ptr<fims_info::Information<double>> info =
        fims_info::Information<double>::GetInstance();

    fims_info::Information<double>::selectivity_models_iterator it;

    // search for maturity in Information
    it = info->selectivity_models.find(this->id);
    // if not found, just return
    if (it == info->selectivity_models.end()) {
      FIMS_WARNING_LOG("Logistic Selectivity " + fims::to_string(this->id) +
                       " not found in Information.");
      return;
    } else {
      std::shared_ptr<fims_popdy::LogisticSelectivity<double>> sel =
          std::dynamic_pointer_cast<fims_popdy::LogisticSelectivity<double>>(
              it->second);

      for (size_t i = 0; i < inflection_point.size(); i++) {
        if (this->inflection_point[i].estimation_type_m.get() == "constant") {
          this->inflection_point[i].final_value_m =
              this->inflection_point[i].initial_value_m;
        } else {
          this->inflection_point[i].final_value_m = sel->inflection_point[i];
        }
      }

      for (size_t i = 0; i < slope.size(); i++) {
        if (this->slope[i].estimation_type_m.get() == "constant") {
          this->slope[i].final_value_m = this->slope[i].initial_value_m;
        } else {
          this->slope[i].final_value_m = sel->slope[i];
        }
      }
    }
  }

  /**
   * @brief Converts the data to json representation for the output.
   * @return A string is returned specifying that the module relates to the
   * selectivity interface with logistic selectivity. It also returns the ID
   * and the parameters. This string is formatted for a json file.
   */
  virtual std::string to_json() {
    std::stringstream ss;

    ss << "{\n";
    ss << " \"module_name\":\"Selectivity\",\n";
    ss << " \"module_type\": \"Logistic\",\n";
    ss << " \"module_id\": " << this->id << ",\n";

    ss << " \"parameters\": [\n{\n";
    ss << "   \"name\": \"inflection_point\",\n";
    ss << "   \"id\":" << this->inflection_point.id_m << ",\n";
    ss << "   \"type\": \"vector\",\n";
    ss << " \"dimensionality\": {\n";
    ss << "  \"header\": [null],\n";
    ss << "  \"dimensions\": [1]\n},\n";
    ss << "   \"values\":" << this->inflection_point << "},\n ";

    ss << "{\n";
    ss << "   \"name\": \"slope\",\n";
    ss << "   \"id\":" << this->slope.id_m << ",\n";
    ss << "   \"type\": \"vector\",\n";
    ss << " \"dimensionality\": {\n";
    ss << "  \"header\": [null],\n";
    ss << "  \"dimensions\": [1]\n},\n";
    ss << "   \"values\":" << this->slope << "}]\n";

    ss << "}";

    return ss.str();
  }

#ifdef TMB_MODEL

  template <typename Type>
  bool add_to_fims_tmb_internal() {
    std::shared_ptr<fims_info::Information<Type>> info =
        fims_info::Information<Type>::GetInstance();

    std::shared_ptr<fims_popdy::LogisticSelectivity<Type>> selectivity =
        std::make_shared<fims_popdy::LogisticSelectivity<Type>>();
    std::stringstream ss;
    // set relative info
    selectivity->id = this->id;
    selectivity->inflection_point.resize(this->inflection_point.size());
    for (size_t i = 0; i < this->inflection_point.size(); i++) {
      selectivity->inflection_point[i] =
          this->inflection_point[i].initial_value_m;
      if (this->inflection_point[i].estimation_type_m.get() ==
          "fixed_effects") {
        ss.str("");
        ss << "Selectivity." << this->id << ".inflection_point."
           << this->inflection_point[i].id_m;
        info->RegisterParameterName(ss.str());
        info->RegisterParameter(selectivity->inflection_point[i]);
      }
      if (this->inflection_point[i].estimation_type_m.get() ==
          "random_effects") {
        ss.str("");
        ss << "Selectivity." << this->id << ".inflection_point."
           << this->inflection_point[i].id_m;
        info->RegisterRandomEffect(selectivity->inflection_point[i]);
        info->RegisterRandomEffectName(ss.str());
      }
    }
    info->variable_map[this->inflection_point.id_m] =
        &(selectivity)->inflection_point;

    selectivity->slope.resize(this->slope.size());
    for (size_t i = 0; i < this->slope.size(); i++) {
      selectivity->slope[i] = this->slope[i].initial_value_m;
      if (this->slope[i].estimation_type_m.get() == "fixed_effects") {
        ss.str("");
        ss << "Selectivity." << this->id << ".slope." << this->slope[i].id_m;
        info->RegisterParameterName(ss.str());
        info->RegisterParameter(selectivity->slope[i]);
      }
      if (this->slope[i].estimation_type_m.get() == "random_effects") {
        ss.str("");
        ss << "Selectivity." << this->id << ".slope." << this->slope[i].id_m;
        info->RegisterRandomEffectName(ss.str());
        info->RegisterRandomEffect(selectivity->slope[i]);
      }
    }
    info->variable_map[this->slope.id_m] = &(selectivity)->slope;

    // add to Information
    info->selectivity_models[selectivity->id] = selectivity;

    return true;
  }

  /**
   * @brief Adds the parameters to the TMB model.
   * @return A boolean of true.
   */
  virtual bool add_to_fims_tmb() {
    this->add_to_fims_tmb_internal<TMB_FIMS_REAL_TYPE>();
    this->add_to_fims_tmb_internal<TMBAD_FIMS_TYPE>();

    return true;
  }

#endif
};
```

AgeSpecificSelectivityInterface:

``` cpp
#| echo: true
#| eval: false
#| code-fold: true
#| code-summary: "Show the code"

class AgeSpecificSelectivityInterface : public SelectivityInterfaceBase {
 public:
   /**
   * @brief The number of age bins.
   */
  SharedInt n_ages = 0; //AJ: should this be set to 0 (as in rcpp_population.hpp, or not?)
  // /**
  // * @brief Vector of ages.
  // */
  //std::vector<int> ages; //AJ: placeholder for reading in ages for calculation of min_age
  RealVector ages;
  // /**
  // * @brief Minimum observed age
  // */
  SharedInt min_age = 0; //AJ: placeholder for calculating minimum age
  /**
   * @brief Age-specific selectivity parameter values.
   */
  ParameterVector logit_sel_at_age;

  /**
   * @brief The constructor.
   */
  AgeSpecificSelectivityInterface() : SelectivityInterfaceBase() {
    SelectivityInterfaceBase::live_objects[this->id] =
        std::make_shared<AgeSpecificSelectivityInterface>(*this);
    FIMSRcppInterfaceBase::fims_interface_objects.push_back(
        SelectivityInterfaceBase::live_objects[this->id]);
  }

  /**
   * @brief Construct a new Selectivity-at-age Interface object
   *
   * @param other
   */
  AgeSpecificSelectivityInterface(const AgeSpecificSelectivityInterface &other)
      : SelectivityInterfaceBase(other),
        n_ages(other.n_ages),
        ages(other.ages), // AJ placeholder
        min_age(other.min_age), // AJ placeholder
        logit_sel_at_age(other.logit_sel_at_age) {}

  /**
   * @brief The destructor.
   */
  virtual ~AgeSpecificSelectivityInterface() {}

  /**
   * @brief Gets the ID of the interface base object.
   * @return The ID.
   */
  virtual uint32_t get_id() { return this->id; }

  /**
   * @brief Evaluate selectivity using fims_math::inv_logit.
   * @param x The independent variable in the logistic function (e.g., age or
   * size in selectivity).
   */
  virtual double evaluate(double x) { 
    fims_popdy::AgeSpecificSelectivity<double> AgeSpecificSel;
    AgeSpecificSel.n_ages = this->n_ages.get(); // AJ: is it necessary to call in n_ages here?
    //AgeSpecificSel.min_age = std::ranges::min(this->ages);

    AgeSpecificSel.min_age = *std::min_element(this->ages.storage_m->begin(), this->ages.storage_m->end()); 
    for (size_t i = 0; i < this->logit_sel_at_age.size(); i++) {
      AgeSpecificSel.logit_sel_at_age[i] = this->logit_sel_at_age[i].initial_value_m;
    } 
    return AgeSpecificSel.evaluate(x); 
  }

  /**
   * @brief Extracts derived quantities back to the Rcpp interface object from
   * the Information object.
   */
  virtual void finalize() {
    if (this->finalized) {
      // log warning that finalize has been called more than once.
      FIMS_WARNING_LOG("Age Specific Selectivity " + fims::to_string(this->id) +
                       " has been finalized already.");
    }

    this->finalized = true;  // indicate this has been called already

    std::shared_ptr<fims_info::Information<double>> info =
        fims_info::Information<double>::GetInstance();

    fims_info::Information<double>::selectivity_models_iterator it;

    // search for maturity in Information
    it = info->selectivity_models.find(this->id);
    // if not found, just return
    if (it == info->selectivity_models.end()) {
      FIMS_WARNING_LOG("Age Specific Selectivity " + fims::to_string(this->id) +
                       " not found in Information.");
      return;
    } else {
      std::shared_ptr<fims_popdy::AgeSpecificSelectivity<double>> sel =
          std::dynamic_pointer_cast<fims_popdy::AgeSpecificSelectivity<double>>(
              it->second);
      for (size_t i = 0; i < logit_sel_at_age.size(); i++) {
        if (this->logit_sel_at_age[i].estimation_type_m.get() == "constant") {
          this->logit_sel_at_age[i].final_value_m =
              this->logit_sel_at_age[i].initial_value_m;
        } else {
          this->logit_sel_at_age[i].final_value_m = sel->logit_sel_at_age[i];
        }
      }
    }
  }

  /**
   * @brief Converts the data to json representation for the output.
   * @return A string is returned specifying that the module relates to the
   * selectivity interface with selectivity-at-age. It also returns the ID
   * and the parameters. This string is formatted for a json file.
   */
  virtual std::string to_json() {
    std::stringstream ss;

    ss << "{\n";
    ss << " \"module_name\":\"Selectivity\",\n";
    ss << " \"module_type\": \"AgeSpecific\",\n";
    ss << " \"module_id\": " << this->id << ",\n";

    ss << " \"parameters\": [\n{\n";
    ss << "   \"name\": \"logit_sel_at_age\",\n";
    ss << "   \"id\":" << this->logit_sel_at_age.id_m << ",\n";
    ss << "   \"type\": \"vector\",\n";
    ss << " \"dimensionality\": {\n";
    ss << "  \"header\": [null],\n";
    // ss << "  \"dimensions\": [1]\n},\n"; //AJ: replaced this line with the lines below
    ss << "  \"dimensions\": [" << this->logit_sel_at_age.size() << "]\n},\n"; 
    ss << "   \"values\":" << this->logit_sel_at_age << "}]\n";

    ss << "}";

    return ss.str();
  }

#ifdef TMB_MODEL

  template <typename Type>
  bool add_to_fims_tmb_internal() {
    std::shared_ptr<fims_info::Information<Type>> info =
        fims_info::Information<Type>::GetInstance();

    std::shared_ptr<fims_popdy::AgeSpecificSelectivity<Type>> selectivity =
        std::make_shared<fims_popdy::AgeSpecificSelectivity<Type>>();
    std::stringstream ss;
    // set relative info
    selectivity->id = this->id;
    selectivity->n_ages = this->n_ages.get();
    selectivity->min_age = *std::min_element(this->ages.storage_m->begin(), this->ages.storage_m->end()); // AJ: placeholder
    selectivity->logit_sel_at_age.resize(this->logit_sel_at_age.size());
    for (size_t i = 0; i < this->logit_sel_at_age.size(); i++) {
      selectivity->logit_sel_at_age[i] =
          this->logit_sel_at_age[i].initial_value_m;
      if (this->logit_sel_at_age[i].estimation_type_m.get() ==
          "fixed_effects") {
        ss.str("");
        ss << "Selectivity." << this->id << ".logit_sel_at_age."
           << this->logit_sel_at_age[i].id_m;
        info->RegisterParameterName(ss.str());
        info->RegisterParameter(selectivity->logit_sel_at_age[i]);
      }
      if (this->logit_sel_at_age[i].estimation_type_m.get() ==
          "random_effects") {
        ss.str("");
        ss << "Selectivity." << this->id << ".logit_sel_at_age."
           << this->logit_sel_at_age[i].id_m;
        info->RegisterRandomEffect(selectivity->logit_sel_at_age[i]);
        info->RegisterRandomEffectName(ss.str());
      }
    }
    info->variable_map[this->logit_sel_at_age.id_m] =
        &(selectivity)->logit_sel_at_age;

    // add to Information
    info->selectivity_models[selectivity->id] = selectivity;

    return true;
  }

  /**
   * @brief Adds the parameters to the TMB model.
   * @return A boolean of true.
   */
  virtual bool add_to_fims_tmb() {
    this->add_to_fims_tmb_internal<TMB_FIMS_REAL_TYPE>();
    this->add_to_fims_tmb_internal<TMBAD_FIMS_TYPE>();

    return true;
  }

#endif
};
```

inst/include/interface/rcpp/rcpp_interface.hpp This is the RCPP
interface "to declare things". We once again copied the code used for
the other selectivity options (i.e., "LogisticSelectivityInterface" and
"DoubleLogisticSelectivityInterface") and copied the code for
AgeSpecificSelectivityInterface

inst/include/population_dynamics/selectivity/selectivity.hpp
src/fims_modules.hpp

And one new file was created:
inst/include/population_dynamics/selectivity/functors/age_specific.hpp

(Using initial numbers-at-age as a scaffold helped) Updating the default
parameters involved updating: create_default_parameters.R

### Specifying default parameters

### :construction: Roadblock #1: Including the minimum age for the age-specific selectivity

(Pulling in others in the Implementation Team to help)

### :construction: Roadblock #2: Flexible indexing options

(Pulling in others in the Implementation Team to help)

### :construction: Roadblock #3: Naming conflicts with other selectivity options

(Add that this issue was caught during a code club, and then plug code
club) Only when we got to building out the vignette to demo the
age-specific selectivity option did we notice a problem with our naming
convention that would conflict with how FIMS builds out names and uses
features. We'd been calling the age-specific option "SelectivityatAge"
but when the create_default_parameters() function is run, this name gets
knitted together with "Selectivity" creating the monstrous
"SelectivityatAgeSelectivity" which FIMS can't understand downstream.

### Final Steps: Model feature testing

## Takeaways

Don't let contributing to FIMS intimidate you! Nobody understands all
the nuanced ins and outs of FIMS except a few core developers and given
the amount of features FIMS needs to meet its 25% by 2026 (25% of NOAA
stocks to be capable of using FIMS to fit the model and generate
management advice), more than that core group needs to be actively
contributing. Take on small tasks at first - a new version of an
existing feature, like these selectivity options. But maximize
efficiency by identifying a feature that is important to several stocks.
Starting small will help build confidence and familiarity with FIMS's
modular nature so you might be comfortable with contributing bigger
changes down the line. Hope this post helps to identify some key
starting spots! Please let us know if you have questions or we can offer
advice, at alexander.jensen\[at\]noaa.gov or
emily.liljestrand\[at\]noaa.gov.
