on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - changelog/FIMS_CHANGELOG.qmd
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

name: Auto Update New FIMS Website Release

jobs:
  website_release:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Set up Node (for Quarto, if needed; remove if not using Quarto)
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Get latest version from changelog
        id: changelog_version
        run: |
          VERSION_HEADING=$(grep -m1 '^## v' changelog/FIMS_CHANGELOG.qmd | sed -E 's/^## (v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?).*/\1/')
          echo "version_heading=$VERSION_HEADING" >> $GITHUB_OUTPUT
      
      # - name: Set environment variable
      #   id: set_env
      #   run: |
      #     VERSION=$(echo "${{ steps.changelog_version.outputs.version_heading }}" | sed 's/^v//')
      #     echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get latest FIMS release tag
        id: fims_release
        run: |
          LATEST_TAG=$(curl --silent "https://api.github.com/repos/NOAA-FIMS/noaa-fims.github.io/releases/latest" | jq -r .tag_name | tr -d ' ')
          echo "fims_website_tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Determine if there is a new fims release
        id: release_updated
        run: |
          if [ "${{ steps.changelog_version.outputs.version_heading }}" != "${{ steps.fims_release.outputs.fims_website_tag }}" ]; then
            echo "release_updated=true" >> $GITHUB_OUTPUT
          else
            echo "release_updated=false" >> $GITHUB_OUTPUT
          fi

      # Use this conditional for all release steps
      - name: Update version in index.qmd
        if: steps.release_updated.outputs.release_updated == 'true'
        run: |
          VERSION=$(echo "${{ steps.changelog_version.outputs.version_heading }}" | sed 's/^v//')
          sed -i -E "s/Version [0-9]+\.[0-9]+\.[0-9]+/Version $VERSION/" index.qmd
          cat index.qmd
          
      # - name: Archive current site to archives folder
      #   if: steps.should_archive.outputs.should_archive == 'true'
      #   run: |
      #     ARCHIVE_DIR="_archives/${{ steps.get_fims_release.outputs.fims_website_tag }}"
      #     mkdir -p "$ARCHIVE_DIR"
      #     cp -rv docs/. "$ARCHIVE_DIR"/
      #     ls _archives
          
      # - name: Commit & Push changes
      #   if: steps.should_archive.outputs.should_archive == 'true'
      #   uses: actions-js/push@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}


      - name: Render Quarto Project
        if: steps.release_updated.outputs.release_updated == 'true'
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: html

      - name: Upload artifact
        if: steps.release_updated.outputs.release_updated == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push rendered site to main
        if: steps.release_updated.outputs.release_updated == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "Update rendered site"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a release with the same tag as the FIMS repo
      - name: Create Release
        if: steps.release_updated.outputs.release_updated == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.changelog_version.outputs.version_heading }}
          name: Release ${{ steps.changelog_version.outputs.version_heading }}
          body: |
            Website release synced with FIMS ${{ steps.changelog_version.outputs.version_heading }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
